version: '2.0'
services:
  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fun
    volumes:
      - /private/var/lib/postgresql:/var/lib/postgresql